on:
  push:
    branches: [ "J2EE" ]

env:
    APPLICATION_NAME: onlinebookstore
    IMAGE_TAG: 0.1

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Build with Maven
      run: mvn -B clean install package --file pom.xml

    - name: Docker Build
      run: docker build -t {{ env.APPLICATION_NAME }}:{{ env.IMAGE_TAG }} .