name: Build Pipeline

# Github Events
on:
  push:
    branches: [ "dev" ]
env:
  APPLICATION_NAME: "onlinebookstore"
  IMAGE_TAG: "0.1"

jobs:
  build:
    runs-on: ubuntu-latest # GitHub Runner
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: maven build
      run: mvn -B clean install package --file pom.xml

    - name: docker build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/$APPLICATION_NAME:$IMAGE_TAG .

    - name: docker login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: docker image push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/$APPLICATION_NAME:$IMAGE_TAG