name: Maven Build Pipeline

# Github Events
on:
  push:
    branches: [ "dev" ]
env:
  APPLICATION_NAME: "onlinebookstore"
  IMAGE_TAG: "0.1"

jobs:
  build:
    runs-on: ubuntu-latest # GitHub Runner
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Maven Build
      run: mvn -B clean install package --file pom.xml

    - name: Docker Build
      run: docker build -t "$APPLICATION_NAME":"$IMAGE_TAG" .